plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.alphamovies.app'
    compileSdk 36

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.alphamovies.app'
        minSdk 23
        targetSdk 36
        versionCode 5
        versionName '1.0.4'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    signingConfigs {
        release {
            def releaseStoreFile = System.getenv("RELEASE_STORE_FILE")
            def releaseStorePassword = System.getenv("RELEASE_STORE_PASSWORD")
            def releaseKeyAlias = System.getenv("RELEASE_KEY_ALIAS")
            def releaseKeyPassword = System.getenv("RELEASE_KEY_PASSWORD")

            if (releaseStoreFile != null && releaseStorePassword != null && releaseKeyAlias != null && releaseKeyPassword != null) {
                storeFile file(releaseStoreFile)
                storePassword releaseStorePassword
                keyAlias releaseKeyAlias
                keyPassword releaseKeyPassword
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix '-debug'
        }
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'com.google.firebase:firebase-messaging:24.0.0'
}
